{{/*
SPDX-License-Identifier: Apache-2.0
Copyright 2026 IT Beratung Hermann GmbH
*/}}
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pdf-ua-generator.fullname" . }}-database
  labels:
    {{- include "pdf-ua-generator.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "database.username is required" .Values.database.username | quote }}
  password: {{ required "database.password or database.existingSecret is required" .Values.database.password | quote }}
{{- end }}
